<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.m6VNrHz' shared service.

return $this->privates['.service_locator.m6VNrHz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'activitecellule' => ['privates', '.errored..service_locator.m6VNrHz.App\\Entity\\Activitecellule', NULL, 'Cannot autowire service ".service_locator.m6VNrHz": it references class "App\\Entity\\Activitecellule" but no such service exists.'],
    'cellule' => ['privates', '.errored..service_locator.m6VNrHz.App\\Entity\\Cellule', NULL, 'Cannot autowire service ".service_locator.m6VNrHz": it references class "App\\Entity\\Cellule" but no such service exists.'],
], [
    'activitecellule' => 'App\\Entity\\Activitecellule',
    'cellule' => 'App\\Entity\\Cellule',
]);
