<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.iZuYVKC' shared service.

return $this->privates['.service_locator.iZuYVKC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService.php', true],
    'zone' => ['privates', '.errored..service_locator.iZuYVKC.App\\Entity\\Zone', NULL, 'Cannot autowire service ".service_locator.iZuYVKC": it references class "App\\Entity\\Zone" but no such service exists.'],
], [
    'userRepository' => 'App\\Repository\\UserRepository',
    'zone' => 'App\\Entity\\Zone',
]);
