<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.htmNKCL' shared service.

return $this->privates['.service_locator.htmNKCL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'cotisationRepository' => ['privates', 'App\\Repository\\CotisationRepository', 'getCotisationRepositoryService.php', true],
    'mois' => ['privates', '.errored..service_locator.htmNKCL.App\\Entity\\Mois', NULL, 'Cannot autowire service ".service_locator.htmNKCL": it references class "App\\Entity\\Mois" but no such service exists.'],
], [
    'cotisationRepository' => 'App\\Repository\\CotisationRepository',
    'mois' => 'App\\Entity\\Mois',
]);
