<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.U0fAqsq' shared service.

return $this->privates['.service_locator.U0fAqsq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'cellule' => ['privates', '.errored..service_locator.U0fAqsq.App\\Entity\\Cellule', NULL, 'Cannot autowire service ".service_locator.U0fAqsq": it references class "App\\Entity\\Cellule" but no such service exists.'],
], [
    'cellule' => 'App\\Entity\\Cellule',
]);
