<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.M3O5_Ap' shared service.

return $this->privates['.service_locator.M3O5_Ap'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'partenairecellule' => ['privates', '.errored..service_locator.M3O5_Ap.App\\Entity\\Partenairecellule', NULL, 'Cannot autowire service ".service_locator.M3O5_Ap": it references class "App\\Entity\\Partenairecellule" but no such service exists.'],
], [
    'partenairecellule' => 'App\\Entity\\Partenairecellule',
]);
