<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.xhIDcZ1' shared service.

return $this->privates['.service_locator.xhIDcZ1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'poste' => ['privates', '.errored..service_locator.xhIDcZ1.App\\Entity\\Poste', NULL, 'Cannot autowire service ".service_locator.xhIDcZ1": it references class "App\\Entity\\Poste" but no such service exists.'],
], [
    'poste' => 'App\\Entity\\Poste',
]);
