<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.3_XQlHf' shared service.

return $this->privates['.service_locator.3_XQlHf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'depense' => ['privates', '.errored..service_locator.3_XQlHf.App\\Entity\\Depense', NULL, 'Cannot autowire service ".service_locator.3_XQlHf": it references class "App\\Entity\\Depense" but no such service exists.'],
], [
    'depense' => 'App\\Entity\\Depense',
]);
