<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.6TL9kNa' shared service.

return $this->privates['.service_locator.6TL9kNa'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'regionRepository' => ['privates', 'App\\Repository\\RegionRepository', 'getRegionRepositoryService.php', true],
    'zone' => ['privates', '.errored..service_locator.6TL9kNa.App\\Entity\\Zone', NULL, 'Cannot autowire service ".service_locator.6TL9kNa": it references class "App\\Entity\\Zone" but no such service exists.'],
], [
    'regionRepository' => 'App\\Repository\\RegionRepository',
    'zone' => 'App\\Entity\\Zone',
]);
