<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.hYdvUlh' shared service.

return $this->privates['.service_locator.hYdvUlh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'rubriqueRepository' => ['privates', 'App\\Repository\\RubriqueRepository', 'getRubriqueRepositoryService.php', true],
], [
    'rubriqueRepository' => 'App\\Repository\\RubriqueRepository',
]);
