<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.6C84.Mo' shared service.

return $this->privates['.service_locator.6C84.Mo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'activiteRepository' => ['privates', 'App\\Repository\\ActiviteRepository', 'getActiviteRepositoryService.php', true],
], [
    'activiteRepository' => 'App\\Repository\\ActiviteRepository',
]);
