<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.dJw1w2C' shared service.

return $this->privates['.service_locator.dJw1w2C'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'cellule' => ['privates', '.errored..service_locator.dJw1w2C.App\\Entity\\Cellule', NULL, 'Cannot autowire service ".service_locator.dJw1w2C": it references class "App\\Entity\\Cellule" but no such service exists.'],
    'partenairecelluleRepository' => ['privates', 'App\\Repository\\PartenairecelluleRepository', 'getPartenairecelluleRepositoryService.php', true],
], [
    'cellule' => 'App\\Entity\\Cellule',
    'partenairecelluleRepository' => 'App\\Repository\\PartenairecelluleRepository',
]);
