<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.2cCyI95' shared service.

return $this->privates['.service_locator.2cCyI95'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'AcquitAssignationRepository' => ['privates', 'App\\Repository\\AcquitAssignationRepository', 'getAcquitAssignationRepositoryService.php', true],
    'assignationRepository' => ['privates', 'App\\Repository\\AssignationRepository', 'getAssignationRepositoryService.php', true],
], [
    'AcquitAssignationRepository' => 'App\\Repository\\AcquitAssignationRepository',
    'assignationRepository' => 'App\\Repository\\AssignationRepository',
]);
