<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.El.2Rap' shared service.

return $this->privates['.service_locator.El.2Rap'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'celluleRepository' => ['privates', 'App\\Repository\\CelluleRepository', 'getCelluleRepositoryService.php', true],
    'zone' => ['privates', '.errored..service_locator.El.2Rap.App\\Entity\\Zone', NULL, 'Cannot autowire service ".service_locator.El.2Rap": it references class "App\\Entity\\Zone" but no such service exists.'],
], [
    'celluleRepository' => 'App\\Repository\\CelluleRepository',
    'zone' => 'App\\Entity\\Zone',
]);
