<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.aqB9CbF' shared service.

return $this->privates['.service_locator.aqB9CbF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'financement' => ['privates', 'App\\Repository\\FinancementRepository', 'getFinancementRepositoryService.php', true],
    'partenaire' => ['privates', '.errored..service_locator.aqB9CbF.App\\Entity\\Partenaire', NULL, 'Cannot autowire service ".service_locator.aqB9CbF": it references class "App\\Entity\\Partenaire" but no such service exists.'],
], [
    'financement' => 'App\\Repository\\FinancementRepository',
    'partenaire' => 'App\\Entity\\Partenaire',
]);
