<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.X3SfHXm' shared service.

return $this->privates['.service_locator.X3SfHXm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'cotismensuelRepository' => ['privates', 'App\\Repository\\CotismensuelRepository', 'getCotismensuelRepositoryService.php', true],
    'user' => ['privates', '.errored..service_locator.X3SfHXm.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.X3SfHXm": it references class "App\\Entity\\User" but no such service exists.'],
], [
    'cotismensuelRepository' => 'App\\Repository\\CotismensuelRepository',
    'user' => 'App\\Entity\\User',
]);
