<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.QW.xD2h' shared service.

return $this->privates['.service_locator.QW.xD2h'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'cellule' => ['privates', '.errored..service_locator.QW.xD2h.App\\Entity\\Cellule', NULL, 'Cannot autowire service ".service_locator.QW.xD2h": it references class "App\\Entity\\Cellule" but no such service exists.'],
    'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService.php', true],
], [
    'cellule' => 'App\\Entity\\Cellule',
    'userRepository' => 'App\\Repository\\UserRepository',
]);
