<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.z7GLnXX' shared service.

return $this->privates['.service_locator.z7GLnXX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'transfert' => ['privates', '.errored..service_locator.z7GLnXX.App\\Entity\\Transfert', NULL, 'Cannot autowire service ".service_locator.z7GLnXX": it references class "App\\Entity\\Transfert" but no such service exists.'],
], [
    'transfert' => 'App\\Entity\\Transfert',
]);
