<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.p9oFLir' shared service.

return $this->privates['.service_locator.p9oFLir'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'cellule' => ['privates', '.errored..service_locator.p9oFLir.App\\Entity\\Cellule', NULL, 'Cannot autowire service ".service_locator.p9oFLir": it references class "App\\Entity\\Cellule" but no such service exists.'],
    'cotisationRepository' => ['privates', 'App\\Repository\\CotisationRepository', 'getCotisationRepositoryService.php', true],
], [
    'cellule' => 'App\\Entity\\Cellule',
    'cotisationRepository' => 'App\\Repository\\CotisationRepository',
]);
