<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.xTUxJFN' shared service.

return $this->privates['.service_locator.xTUxJFN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'cellule' => ['privates', '.errored..service_locator.xTUxJFN.App\\Entity\\Cellule', NULL, 'Cannot autowire service ".service_locator.xTUxJFN": it references class "App\\Entity\\Cellule" but no such service exists.'],
    'transfertcellule' => ['privates', '.errored..service_locator.xTUxJFN.App\\Entity\\Transfertcellule', NULL, 'Cannot autowire service ".service_locator.xTUxJFN": it references class "App\\Entity\\Transfertcellule" but no such service exists.'],
], [
    'cellule' => 'App\\Entity\\Cellule',
    'transfertcellule' => 'App\\Entity\\Transfertcellule',
]);
