<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.lxZFsv1' shared service.

return $this->privates['.service_locator.lxZFsv1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'autreentreecellule' => ['privates', '.errored..service_locator.lxZFsv1.App\\Entity\\Autreentreecellule', NULL, 'Cannot autowire service ".service_locator.lxZFsv1": it references class "App\\Entity\\Autreentreecellule" but no such service exists.'],
    'cellule' => ['privates', '.errored..service_locator.lxZFsv1.App\\Entity\\Cellule', NULL, 'Cannot autowire service ".service_locator.lxZFsv1": it references class "App\\Entity\\Cellule" but no such service exists.'],
], [
    'autreentreecellule' => 'App\\Entity\\Autreentreecellule',
    'cellule' => 'App\\Entity\\Cellule',
]);
