<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.XYCzuU4' shared service.

return $this->privates['.service_locator.XYCzuU4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'autreentreeRepository' => ['privates', 'App\\Repository\\AutreentreeRepository', 'getAutreentreeRepositoryService.php', true],
], [
    'autreentreeRepository' => 'App\\Repository\\AutreentreeRepository',
]);
