<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.FKuzTMK' shared service.

return $this->privates['.service_locator.FKuzTMK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'autreentree' => ['privates', '.errored..service_locator.FKuzTMK.App\\Entity\\Autreentree', NULL, 'Cannot autowire service ".service_locator.FKuzTMK": it references class "App\\Entity\\Autreentree" but no such service exists.'],
], [
    'autreentree' => 'App\\Entity\\Autreentree',
]);
