<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Q5GLSgu' shared service.

return $this->privates['.service_locator.Q5GLSgu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'rubrique' => ['privates', '.errored..service_locator.Q5GLSgu.App\\Entity\\Rubrique', NULL, 'Cannot autowire service ".service_locator.Q5GLSgu": it references class "App\\Entity\\Rubrique" but no such service exists.'],
], [
    'rubrique' => 'App\\Entity\\Rubrique',
]);
