<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.u2tvvIj' shared service.

return $this->privates['.service_locator.u2tvvIj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'autreentreecellule' => ['privates', '.errored..service_locator.u2tvvIj.App\\Entity\\Autreentreecellule', NULL, 'Cannot autowire service ".service_locator.u2tvvIj": it references class "App\\Entity\\Autreentreecellule" but no such service exists.'],
], [
    'autreentreecellule' => 'App\\Entity\\Autreentreecellule',
]);
