<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.XC.958p' shared service.

return $this->privates['.service_locator.XC.958p'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'cellule' => ['privates', '.errored..service_locator.XC.958p.App\\Entity\\Cellule', NULL, 'Cannot autowire service ".service_locator.XC.958p": it references class "App\\Entity\\Cellule" but no such service exists.'],
    'partenairecellule' => ['privates', '.errored..service_locator.XC.958p.App\\Entity\\Partenairecellule', NULL, 'Cannot autowire service ".service_locator.XC.958p": it references class "App\\Entity\\Partenairecellule" but no such service exists.'],
], [
    'cellule' => 'App\\Entity\\Cellule',
    'partenairecellule' => 'App\\Entity\\Partenairecellule',
]);
