<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ttKZw3M' shared service.

return $this->privates['.service_locator.ttKZw3M'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'cellule' => ['privates', '.errored..service_locator.ttKZw3M.App\\Entity\\Cellule', NULL, 'Cannot autowire service ".service_locator.ttKZw3M": it references class "App\\Entity\\Cellule" but no such service exists.'],
    'financement' => ['privates', 'App\\Repository\\FinancementcelluleRepository', 'getFinancementcelluleRepositoryService.php', true],
    'partenairecellule' => ['privates', '.errored..service_locator.ttKZw3M.App\\Entity\\Partenairecellule', NULL, 'Cannot autowire service ".service_locator.ttKZw3M": it references class "App\\Entity\\Partenairecellule" but no such service exists.'],
    'partenairecelluleRepository' => ['privates', 'App\\Repository\\PartenairecelluleRepository', 'getPartenairecelluleRepositoryService.php', true],
], [
    'cellule' => 'App\\Entity\\Cellule',
    'financement' => 'App\\Repository\\FinancementcelluleRepository',
    'partenairecellule' => 'App\\Entity\\Partenairecellule',
    'partenairecelluleRepository' => 'App\\Repository\\PartenairecelluleRepository',
]);
