<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.o8nqixb' shared service.

return $this->privates['.service_locator.o8nqixb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'assignationRepository' => ['privates', 'App\\Repository\\AssignationRepository', 'getAssignationRepositoryService.php', true],
], [
    'assignationRepository' => 'App\\Repository\\AssignationRepository',
]);
