<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.fhD6Kl6' shared service.

return $this->privates['.service_locator.fhD6Kl6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'activitecellule' => ['privates', '.errored..service_locator.fhD6Kl6.App\\Entity\\Activitecellule', NULL, 'Cannot autowire service ".service_locator.fhD6Kl6": it references class "App\\Entity\\Activitecellule" but no such service exists.'],
], [
    'activitecellule' => 'App\\Entity\\Activitecellule',
]);
