<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.fk138Gw' shared service.

return $this->privates['.service_locator.fk138Gw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'cotismensuelRepository' => ['privates', 'App\\Repository\\CotismensuelRepository', 'getCotismensuelRepositoryService.php', true],
    'mois' => ['privates', '.errored..service_locator.fk138Gw.App\\Entity\\Mois', NULL, 'Cannot autowire service ".service_locator.fk138Gw": it references class "App\\Entity\\Mois" but no such service exists.'],
], [
    'cotismensuelRepository' => 'App\\Repository\\CotismensuelRepository',
    'mois' => 'App\\Entity\\Mois',
]);
