<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.GmNA5gD' shared service.

return $this->privates['.service_locator.GmNA5gD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'zone' => ['privates', '.errored..service_locator.GmNA5gD.App\\Entity\\Zone', NULL, 'Cannot autowire service ".service_locator.GmNA5gD": it references class "App\\Entity\\Zone" but no such service exists.'],
], [
    'zone' => 'App\\Entity\\Zone',
]);
