<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.7IRBQJH' shared service.

return $this->privates['.service_locator.7IRBQJH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'cellule' => ['privates', '.errored..service_locator.7IRBQJH.App\\Entity\\Cellule', NULL, 'Cannot autowire service ".service_locator.7IRBQJH": it references class "App\\Entity\\Cellule" but no such service exists.'],
    'user' => ['privates', '.errored..service_locator.7IRBQJH.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.7IRBQJH": it references class "App\\Entity\\User" but no such service exists.'],
], [
    'cellule' => 'App\\Entity\\Cellule',
    'user' => 'App\\Entity\\User',
]);
