<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.ki95jtI.App\Entity\Activite' shared service.

$this->throw('Cannot autowire service ".service_locator.ki95jtI": it references class "App\\Entity\\Activite" but no such service exists.');
