<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.u2tvvIj.App\Entity\Autreentreecellule' shared service.

$this->throw('Cannot autowire service ".service_locator.u2tvvIj": it references class "App\\Entity\\Autreentreecellule" but no such service exists.');
