<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.p9oFLir.App\Entity\Cellule' shared service.

$this->throw('Cannot autowire service ".service_locator.p9oFLir": it references class "App\\Entity\\Cellule" but no such service exists.');
