<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.dJw1w2C.App\Entity\Cellule' shared service.

$this->throw('Cannot autowire service ".service_locator.dJw1w2C": it references class "App\\Entity\\Cellule" but no such service exists.');
