<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.sR5jvIB.App\Entity\Cotisation' shared service.

$this->throw('Cannot autowire service ".service_locator.sR5jvIB": it references class "App\\Entity\\Cotisation" but no such service exists.');
