<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.HD5UmlK.App\Entity\Depensecellule' shared service.

$this->throw('Cannot autowire service ".service_locator.HD5UmlK": it references class "App\\Entity\\Depensecellule" but no such service exists.');
