<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Complement\Mois' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/Complement/Mois.php';

return $this->privates['App\\Complement\\Mois'] = new \App\Complement\Mois();
