<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.fk138Gw.App\Entity\Mois' shared service.

$this->throw('Cannot autowire service ".service_locator.fk138Gw": it references class "App\\Entity\\Mois" but no such service exists.');
