<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.M3O5_Ap.App\Entity\Partenairecellule' shared service.

$this->throw('Cannot autowire service ".service_locator.M3O5_Ap": it references class "App\\Entity\\Partenairecellule" but no such service exists.');
