<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.xhIDcZ1.App\Entity\Poste' shared service.

$this->throw('Cannot autowire service ".service_locator.xhIDcZ1": it references class "App\\Entity\\Poste" but no such service exists.');
