<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.Q5GLSgu.App\Entity\Rubrique' shared service.

$this->throw('Cannot autowire service ".service_locator.Q5GLSgu": it references class "App\\Entity\\Rubrique" but no such service exists.');
