<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.iZuYVKC.App\Entity\Zone' shared service.

$this->throw('Cannot autowire service ".service_locator.iZuYVKC": it references class "App\\Entity\\Zone" but no such service exists.');
