<?php

namespace App\Repository;

/**
 * DebitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DebitRepository extends \Doctrine\ORM\EntityRepository
{

    public function etatmensuel($annee)
	{
		$mois = date('Y')."-".date('m')."-01";
		return $this->createQueryBuilder('d')
        ->Where('d.date > :val')
        ->setParameter('val', $mois)
            ->andWhere('d.annee = :annee')
            ->setParameter('annee', $annee)
            ->getQuery()
            ->getResult()
        ;
	}

    public function brouyard()
	{
		$query = $this->createQueryBuilder('a')
					->Where('a.date = :genre')
					->setParameter('genre', date('Y-m-d'))
					->getQuery();
		return $query->getResult();
	}
	public function daybrouyard($date)
	{
		$query = $this->createQueryBuilder('a')
					->Where('a.date = :genre')
					->setParameter('genre', $date)
					->getQuery();
		return $query->getResult();
	}

	public function plage($date, $date1)
	{
		$query = $this->createQueryBuilder('a')
					->andWhere('a.date BETWEEN :debut AND :fin')
					->setParameter('debut', $date)
					->setParameter('fin', $date1)
					->getQuery();
		return $query->getResult();
	}

	public function ouverture()
	{
		$query = $this->createQueryBuilder('a')
					->Where('a.date < :genre')
					->setParameter('genre', date('Y-m-d'))
					->getQuery();
		return $query->getResult();
	}

	public function ouvertureplage($datedebut)
	{
		$query = $this->createQueryBuilder('a')
					->Where('a.date < :genre')
					->setParameter('genre', $datedebut)
					->getQuery();
		return $query->getResult();
	}
}
