<?php

namespace App\Repository;

/**
 * DepenseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepenseRepository extends \Doctrine\ORM\EntityRepository
{

    public function etatmensuel($annee)
	{
		$mois = date('Y')."-".date('m')."-01";
		return $this->createQueryBuilder('d')
        ->Where('d.date > :val')
        ->setParameter('val', $mois)
            ->andWhere('d.annee = :annee')
            ->setParameter('annee', $annee)
            ->getQuery()
            ->getResult()
        ;
	}
}
