<?php

namespace App\Repository;

/**
 * MoisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoisRepository extends \Doctrine\ORM\EntityRepository
{
}
