<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXxbjv64\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXxbjv64/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXxbjv64.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXxbjv64\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXxbjv64\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Xxbjv64',
    'container.build_id' => '54b7b2d1',
    'container.build_time' => 1713714956,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXxbjv64');
